{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Projetos\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.121.644.0 (23.09)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "medidas.oportunidades_de_projeto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Oportunidades de projeto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Oportunidades": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "2b2071a4-e264-41af-897c-3eebc598e5f7",
        "fromColumn": "Data Ativação Lead",
        "fromTable": "Projetos",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_439eee42-ee27-458c-a63e-0f059517ebdf"
      },
      {
        "name": "4c91d9e5-598f-4bbc-8c6f-8ab19cec654b",
        "fromColumn": "Data Início",
        "fromTable": "Projetos",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8727fff2-a9e3-4dbe-bbea-847f386ac637"
      },
      {
        "name": "13c561a8-8e98-4daa-b784-27a7c0a2ecc0",
        "fromColumn": "Data Termino",
        "fromTable": "Projetos",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5f099f2b-b455-4fda-8f38-94ca5dd02830"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Projetos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Código Projeto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0857fe16-2330-4510-9616-e81c6c362339",
            "sourceColumn": "Código Projeto",
            "summarizeBy": "none"
          },
          {
            "name": "Setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14e81b54-0496-4eb3-af03-f37e71e4f778",
            "sourceColumn": "Setor",
            "summarizeBy": "none"
          },
          {
            "name": "Valor Orçado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9de33ee3-43bd-4620-aabb-b1e24c004a0b",
            "sourceColumn": "Valor Orçado",
            "summarizeBy": "sum"
          },
          {
            "name": "Valor Negociado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3d7c7e5c-2053-4a46-b256-2aecaa73be94",
            "sourceColumn": "Valor Negociado",
            "summarizeBy": "sum"
          },
          {
            "name": "Desconto Concedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "86b2f231-5627-4aa7-a43c-a772cbac4b5c",
            "sourceColumn": "Desconto Concedido",
            "summarizeBy": "sum"
          },
          {
            "name": "Data Ativação Lead",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3a1251c1-8085-4ab1-a01c-045a222f736f",
            "sourceColumn": "Data Ativação Lead",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_439eee42-ee27-458c-a63e-0f059517ebdf"
                },
                "isDefault": true,
                "relationship": "2b2071a4-e264-41af-897c-3eebc598e5f7"
              }
            ]
          },
          {
            "name": "Data Início",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8f67b085-a98c-4ab9-b9ae-1f8ec40b427f",
            "sourceColumn": "Data Início",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_8727fff2-a9e3-4dbe-bbea-847f386ac637"
                },
                "isDefault": true,
                "relationship": "4c91d9e5-598f-4bbc-8c6f-8ab19cec654b"
              }
            ]
          },
          {
            "name": "Data Termino",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "618747e4-140b-447b-93b1-85314ee5042e",
            "sourceColumn": "Data Termino",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_5f099f2b-b455-4fda-8f38-94ca5dd02830"
                },
                "isDefault": true,
                "relationship": "13c561a8-8e98-4daa-b784-27a7c0a2ecc0"
              }
            ]
          },
          {
            "name": "Responsável",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5937aa3-d12a-4fb1-849b-0ab013b2b851",
            "sourceColumn": "Responsável",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6bc441fa-f354-4c7a-b612-b62e695f9fa8",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a22b133c-bd99-494d-8e0e-8f302503fdda",
        "partitions": [
          {
            "name": "Projetos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"C:\\Users\\erickss\\Downloads\\Base Projetos.xlsx\"), null, true),",
                "    Projetos_Sheet = Fonte{[Item=\"Projetos\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Projetos_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Código Projeto\", type text}, {\"Setor\", type text}, {\"Valor Orçado\", Int64.Type}, {\"Valor Negociado\", Int64.Type}, {\"Desconto Concedido\", Int64.Type}, {\"Data Ativação Lead\", type date}, {\"Data Início\", type date}, {\"Data Termino\", type date}, {\"Responsável\", type text}, {\"Status\", type text}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each true),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Valor Negociado\", type number}, {\"Valor Orçado\", type number}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ad67e8ff-eeff-46c3-8351-0b27f7024d55",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8f4d4945-9c81-4145-84dc-ef71c2b8e3d1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0e452672-46e9-4bf7-8929-cc8d8206ba29",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c31afd0a-bbc1-4883-adf9-b856dd404942",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c71daf0c-25d2-450a-8f90-5c227d978e9b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d3752db9-fbad-450a-9787-982287186bb0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c25127e2-21f4-41eb-8c0e-b656aa2ce006",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1e3d2ae5-a12e-46c2-a346-3d3db76bb46b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "947869fa-193a-4d44-92df-da89d64f39f1",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "5e311d33-ab4e-4e76-8de0-260c854cba42",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "a3a382e5-1ea7-47d5-ab62-de19fee88260",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "deabcca7-f88b-4034-8053-c29a6d3bb336",
                "ordinal": 3
              }
            ],
            "lineageTag": "a4bc39c5-c982-4ee8-8276-50104602a2ed"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "fbc458e2-1d3d-40fc-92ca-76a22fe6304e",
        "partitions": [
          {
            "name": "DateTableTemplate_ad67e8ff-eeff-46c3-8351-0b27f7024d55",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_439eee42-ee27-458c-a63e-0f059517ebdf",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "22288f08-cb37-40fd-834d-91492d730594",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "74ee2b22-2ccf-42ed-9334-74f7a5ffa2b8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "afc9ae54-57a6-428e-a60c-fe8b42803174",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e922ddb5-654a-4707-b708-3e3f566c6617",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6c323cba-ab93-4499-b3b8-853220eec846",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5773aaaf-216e-4193-9045-5f988c9fc8dc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5a5f598c-323b-4849-b60b-2f1d439c53bd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "edaeef51-5c03-4581-a81e-292e2af9bfe4",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "537f5fd6-48d2-4e7f-b487-f9efcb30d961",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "e0530869-e50d-42b0-bf08-48ea3f5f67af",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "fd5a64c1-7342-4996-b4eb-9f0016294785",
                "ordinal": 3
              }
            ],
            "lineageTag": "bf903110-73aa-4806-80e0-3215bbca85fd"
          }
        ],
        "isHidden": true,
        "lineageTag": "78019b7f-3be0-4725-a7a1-bc2c9fb6cb5e",
        "partitions": [
          {
            "name": "LocalDateTable_439eee42-ee27-458c-a63e-0f059517ebdf",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Projetos'[Data Ativação Lead])), 1, 1), Date(Year(MAX('Projetos'[Data Ativação Lead])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_8727fff2-a9e3-4dbe-bbea-847f386ac637",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9c281f21-d541-486f-90f2-a43e05be65c5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "531af1c9-5f9e-44b2-9175-a9d2691a9dc4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f4a1eee6-8e78-4a57-be54-da884a3660e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "887ad720-6b4e-4081-a0f6-cba3cae6dd58",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d6d9d1e1-5a6f-41c8-8612-bea1e316feb4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "07e46349-cdba-4908-a1cc-21a9d1fe73aa",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "40545d99-e329-4d0d-be05-5c426b285f8b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "b4a664ad-f3b9-453e-b4e4-ffce5a9fbf10",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "964b52ce-0fa2-4a90-a7eb-c8ddf3582933",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "3c55a07e-2ff2-42a3-a9ab-0f6bf099e16c",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "e9d7e77f-3c97-4bd3-aed8-bbc645c291df",
                "ordinal": 3
              }
            ],
            "lineageTag": "01c13426-e80e-4339-a342-e1151b4036c0"
          }
        ],
        "isHidden": true,
        "lineageTag": "ebc4aaa0-0bad-4051-a6c0-9021fea50d41",
        "partitions": [
          {
            "name": "LocalDateTable_8727fff2-a9e3-4dbe-bbea-847f386ac637",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Projetos'[Data Início])), 1, 1), Date(Year(MAX('Projetos'[Data Início])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_5f099f2b-b455-4fda-8f38-94ca5dd02830",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2393a820-e3f7-4c7b-b4ac-221db1b0c45c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "80f308a0-a178-4b4b-8487-d51db4290af6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "98d5e3cb-338f-4cca-be7d-1a68495c7d79",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a3bfd172-7a23-49ad-be4d-26e85de4b580",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a74511c4-ca61-4414-a621-a2419633446c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a2697b4c-9b91-4e1d-bf89-b45ecb3030bb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8de5d5ab-f36c-4446-bc76-2bf4ae77b9fb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "0d2ad72a-8608-49d3-837f-1f762211b261",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "3c0cd172-b1cc-4f3a-9e62-af5fa9e8e191",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "90ecbd53-e942-4a05-a50f-04746bbb4a19",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "247807a5-9fe1-4261-86d7-ebca5235b633",
                "ordinal": 3
              }
            ],
            "lineageTag": "cff17066-ac6c-4010-9f84-46cccef4df29"
          }
        ],
        "isHidden": true,
        "lineageTag": "476eb732-5e8e-440c-94a7-0a9ceb863836",
        "partitions": [
          {
            "name": "LocalDateTable_5f099f2b-b455-4fda-8f38-94ca5dd02830",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Projetos'[Data Termino])), 1, 1), Date(Year(MAX('Projetos'[Data Termino])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0b329fed4d4f44dd9ae0a8eebda37bd7"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b3159c5d-4aee-4950-a398-1e7c71453371",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "5aba37f2-f0f9-496b-973a-88c8706cb7ff",
        "measures": [
          {
            "name": "Oportunidades de projeto",
            "expression": "DISTINCTCOUNT(Projetos[Código Projeto])",
            "formatString": "0",
            "lineageTag": "e98bf8df-9ed3-4bdc-8361-13ec20ca694d"
          },
          {
            "name": "Projetos Fechados",
            "expression": [
              "CALCULATE(",
              "    COUNTROWS(Projetos), ",
              "    Projetos[Data Início] <> BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "69b53de4-f510-4f17-ad98-931e8761dd1e"
          },
          {
            "name": "Total Leads",
            "expression": "CALCULATE(COUNT(Projetos[Data Ativação Lead]), Projetos[Data Início] = BLANK())",
            "formatString": "0",
            "lineageTag": "ae61eb52-f392-4518-97dd-ffe69e25cd6e"
          },
          {
            "name": "Total Orçado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "CALCULATE(SUM(Projetos[Valor Orçado]), Projetos[Data Início] <> BLANK())",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "bfdaf4dc-500e-4b8d-8ddb-a2d7bbb4202d"
          },
          {
            "name": "Total Pago",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "CALCULATE(SUM(Projetos[Valor Negociado]), Projetos[Data Início] <> BLANK())",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "41e45872-4605-4411-b019-b5a23a30e287"
          },
          {
            "name": "Total Desconto",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "[Total Orçado] - [Total Pago]",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "4c770929-ebc7-4ff4-97be-45023f070d9b"
          },
          {
            "name": "Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "SUM(Projetos[Valor Orçado])",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "d7575efa-ae32-4122-9c64-aa85447ba099"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}